name: TypeScript Build and FTP Upload

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '20'

    - name: Install dependencies
      run: npm install

    - name: Build
      run: PUBLIC_URL=https://edu.hoffmannc.net/classroom npm run build

    - name: Upload to FTP
      uses: pressidium/lftp-mirror-action@v1
      with:
        host: ${{ secrets.FTP_SERVER }}
        user: ${{ secrets.FTP_USERNAME }}
        pass: ${{ secrets.FTP_PASSWORD }}
        onlyNewer: true
        reverse: true
        localDir: './build'
        remoteDir: '/edu/classroom'
        options: '--verbose'